name: Build

on:
  push:
    branches: [master, ci-test]
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  release:
    name: CI Test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Create Build Directory
        run: cmake -E make_directory ${{github.workspace}}/build
        
      - name: Install Eigen
        run: |
            sudo apt-get update
            sudo apt-get install libeigen3-dev
            
      - name: Configure Cmake
        run: |
            cd ${{github.workspace}}/build
            cmake ..
      - name: Build
        run: make
